---
- name: Install Kubernetes on all nodes
  hosts: all
  become: true
  tasks:
    - name: Configure sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl changes
      command: sysctl --system


    - name: Disable swap temporarily
      command: swapoff -a

    - name: Ensure swap is disabled on boot
      replace:
        path: /etc/fstab
        regexp: '^(.*\s+swap\s+.*)$'
        replace: '#\1'

    - name: Install apt-transport-https, ca-certificates, and curl
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Check if the GPG file exists
      ansible.builtin.stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: file_check

    - name: Add Kubernetes GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      when: not file_check.stat.exists

    - name: Update apt package index
      apt:
        update_cache: yes
      
    - name: Add Kubernetes repository to apt sources
      shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present


    - name: Hold kubelet, kubeadm, and kubectl at current version
      shell: |
        apt-mark hold kubelet kubeadm kubectl

    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: true

